[build-system]
requires = [
  "setuptools>=64",
  "wheel",
  "pybind11>=2.11",
]
build-backend = "setuptools.build_meta"

[project]
name = "clonify"
version = "0.0.0"
description = "Robust average-linkage antibody clustering"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "Bryan Briney" }]
dependencies = [
  "pandas>=1.5; python_version < '3.12'",
  "pandas>=2.0; python_version >= '3.12'",
  "polars>=0.19",
  "click>=8.1",
]

[project.urls]
Homepage = "https://github.com/bryanbriney/clonify"

[tool.setuptools]
packages = ["clonify"]

[tool.setuptools.package-data]
clonify = []

[project.scripts]
clonify = "clonify.cli:clonify"

