name: Publish to PyPI on release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      publish_target:
        description: Where to publish artifacts
        required: true
        type: choice
        options: [none, testpypi, pypi]
        default: none

permissions:
  contents: read

jobs:
  build-wheels:
    name: Build wheels (${{ matrix.os }} / py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheel (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          maturin-version: latest
          manylinux: auto
          args: --release --out dist

      - name: Build wheel (macOS universal2)
        if: startsWith(matrix.os, 'macos')
        uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          maturin-version: latest
          args: --release --out dist --universal2

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*.whl
          if-no-files-found: error

  sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build sdist with maturin
        uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          maturin-version: latest
          command: sdist
          args: --out dist

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          if-no-files-found: error

  smoke-test:
    name: Smoke test install (${{ matrix.os }} / py${{ matrix.python-version }})
    needs: [build-wheels]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
        python-version: ["3.10", "3.12"]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Install wheel from artifacts
        run: |
          python -m pip install -U pip
          python -m pip install --no-index --find-links dist --only-binary clonify clonify
      - name: Import and CLI smoke test
        run: |
          python - <<'PY'
          import clonify, importlib
          importlib.import_module("clonify._native")
          print("Imported clonify", clonify.__version__)
          PY
          clonify --help

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build-wheels, sdist, smoke-test]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.publish_target == 'pypi')
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          packages-dir: dist
          verbose: true
          skip-existing: true

      - name: Publish to TestPyPI
        if: github.event_name == 'workflow_dispatch' && inputs.publish_target == 'testpypi'
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          packages-dir: dist
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          skip-existing: true


